// Layout only. Steam's components own fonts, surfaces, buttons and focus states.
export const nativeStyles = `
.orbiter{box-sizing:border-box;min-width:0;background:transparent;color:inherit}
.orbiter h1{font:inherit;font-weight:600;margin:0}.orbiter h2{font:inherit;font-weight:600;margin:0 0 8px}.orbiter p{margin:6px 0 12px}
.orbiter .orb-head,.orbiter .orb-flex{display:flex;align-items:center;justify-content:space-between;gap:8px}.orbiter .orb-head{margin-bottom:12px}.orbiter .orb-brand{display:flex;align-items:center;gap:8px}
.orbiter .orb-button{box-sizing:border-box;min-width:0!important;max-width:100%;width:100%;white-space:normal}.orbiter .orb-icon-button{width:38px!important;height:38px;min-width:38px!important;max-width:38px;min-height:38px;flex:0 0 38px!important;padding:0;display:flex;align-items:center;justify-content:center}
.orbiter .orb-status{display:flex;gap:6px;align-items:center}.orbiter .orb-dot{width:5px;height:5px;border-radius:50%;background:currentColor;flex:none}.orbiter .idle{opacity:.5}.orbiter .orb-tag,.orbiter .orb-map,.orbiter .orb-small,.orbiter .orb-subtitle,.orbiter .orb-footnote{font-size:12px;opacity:.75}
.orbiter .orb-tabs{display:flex;gap:8px;margin:16px 0}.orbiter .orb-tabs>*{flex:1;min-width:0}.orbiter .orb-section{margin:18px 0}.orbiter .orb-section-head{display:flex;justify-content:space-between;align-items:center}
.orbiter .orb-row{display:flex;gap:8px;align-items:center;padding:12px 0}.orbiter .orb-condition-icon{width:24px;height:28px;object-fit:contain;flex:none}.orbiter .orb-fallback{width:24px;flex:none;text-align:center}.orbiter .orb-details{flex:1;min-width:0}.orbiter .orb-name{font-size:14px;font-weight:600;overflow-wrap:anywhere}.orbiter .orb-map{margin-top:3px}.orbiter .orb-time{text-align:right;white-space:nowrap;font-size:12px;font-variant-numeric:tabular-nums}.orbiter .orb-time strong{display:block}.orbiter .orb-time small{font-size:10px}.orbiter .orb-star{width:32px;height:32px;min-width:32px;min-height:32px;flex:0 0 32px;padding:0;display:flex;align-items:center;justify-content:center}
.orbiter .orb-footer{margin-top:18px}.orbiter .orb-footer>.orb-button{width:100%}.orbiter .orb-footer>.orb-button+.orb-flex{margin-top:10px}.orbiter .orb-footer .orb-flex>.orb-button{flex:1}.orbiter .orb-footnote{display:flex;justify-content:space-between;gap:8px;margin-top:12px}.orbiter .orb-back{margin-bottom:16px}.orbiter .orb-empty,.orbiter .orb-message{padding:12px 0}.orbiter .orb-setting{margin:14px 0}.orbiter .orb-manage{width:100%;margin-top:8px}
.orbiter .orb-condition-list{margin-top:12px}.orbiter .orb-condition-choice{margin-bottom:8px}.orbiter .orb-condition-heading{display:flex;align-items:center;gap:6px}.orbiter .orb-condition-toggle{display:flex;gap:8px;align-items:center;flex:1;min-width:0;white-space:normal}.orbiter .orb-condition-copy{display:flex;flex-direction:column;gap:3px;flex:1;min-width:0;text-align:left}.orbiter .orb-choice-name{font-size:14px;font-weight:600;overflow-wrap:anywhere}.orbiter .orb-choice-summary{font-size:12px;opacity:.75;overflow-wrap:anywhere}.orbiter .orb-selection-mark{flex:none}.orbiter .orb-map-expander{width:38px;height:38px;min-width:38px;min-height:38px;flex:0 0 38px;padding:0;display:flex;align-items:center;justify-content:center}.orbiter .orb-disclosure-slot{display:flex;align-items:center;justify-content:center;width:38px;height:38px}.orbiter .orb-chevron{width:16px;height:16px;display:block}.orbiter .orb-chevron.open{transform:rotate(180deg)}
.orbiter .orb-map-options{display:flex;flex-direction:column;gap:6px;padding:12px 0}.orbiter .orb-map-options .orb-button{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;white-space:normal}.orbiter .orb-filter-list{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.orbiter .orb-support{font-size:12px}.orbiter.orb-wide{max-width:980px;margin:auto;padding:24px}.orbiter.orb-wide .orb-columns{display:grid;grid-template-columns:1fr 1fr;gap:24px}.orbiter .orb-setup-title{margin-top:20px}
@media(max-width:650px){.orbiter.orb-wide .orb-columns{display:block}}
.orbiter .orb-flex>.orb-button,.orbiter .orb-tabs>.orb-button{width:0;flex:1 1 0!important;min-width:0!important}
.orbiter .orb-tabs{align-items:stretch}.orbiter .orb-back{width:auto}.orbiter .orb-head>.orb-icon-button{width:38px!important}
.orbiter .orb-star{width:32px!important;max-width:32px;min-width:32px!important;flex:0 0 32px!important}
.orbiter .orb-map-expander{width:38px!important;max-width:38px;min-width:38px!important;flex:0 0 38px!important}
.orbiter .orb-condition-toggle{width:0;flex:1 1 0!important}.orbiter .orb-footnote{flex-wrap:wrap}
.orbiter .orb-message{overflow-wrap:anywhere}
.orbiter .orb-inline-choice{margin:0}.orbiter .orb-inline-choice-trigger,.orbiter .orb-inline-choice-option{display:flex;align-items:center;justify-content:space-between;gap:8px}
.orbiter .orb-inline-choice-options{display:flex;flex-direction:column;gap:6px;margin-top:8px}.orbiter .orb-inline-choice-trigger .orb-disclosure-slot{width:16px;height:16px;flex:0 0 16px}
.orbiter .orb-page-head{display:flex;align-items:center;gap:10px;margin-bottom:16px}.orbiter .orb-page-head .orb-back{width:38px!important;height:38px;min-width:38px!important;max-width:38px;flex:0 0 38px!important;padding:0;margin:0}.orbiter .orb-page-head h1{flex:1;min-width:0}.orbiter .orb-page-head .orb-support{width:auto}
.orbiter .orb-status{min-width:0;flex:1;flex-wrap:wrap}.orbiter .orb-tag{flex:none}.orbiter .orb-footnote{line-height:1.4}.orbiter .orb-setup-title{margin-top:0}
`;
