export const styles = `
.orbiter{--ink:#ebe4d4;--muted:#929993;--line:#ffffff13;--accent:#e3a072;color:var(--ink);background:#1c2427;font:14px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:.01em;min-height:100%;box-sizing:border-box;padding:20px 18px 16px}
.orbiter *{box-sizing:border-box}.orbiter h1,.orbiter h2,.orbiter p{margin:0}.orbiter h1{font-size:22px;font-weight:650;letter-spacing:-.04em}.orbiter h2{font-size:11px;font-weight:650;letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}
.orbiter .orb-button{border:1px solid var(--line)!important;background:#ffffff05!important;color:var(--ink)!important;border-radius:7px!important;padding:9px 11px!important;min-width:0!important;min-height:0!important;font:inherit!important;box-shadow:none!important;cursor:pointer;text-align:left;display:block;width:auto}
.orbiter .orb-button:hover{background:#ffffff0c!important}.orbiter .orb-button:focus-visible,.orbiter .orb-button.gpfocus{outline:2px solid var(--accent)!important;outline-offset:2px}.orbiter .orb-button:disabled{opacity:.4;cursor:wait}.orbiter .orb-button.selected{background:#e3a07215!important;border-color:#e3a07255!important;color:#f1bb95!important}
.orbiter .orb-head,.orbiter .orb-flex{display:flex;align-items:center;justify-content:space-between;gap:8px}.orbiter .orb-head{margin-bottom:12px}.orbiter .orb-brand{display:flex;gap:9px;align-items:center}.orbiter .orb-symbol{color:var(--accent);font-size:27px;line-height:1}.orbiter .orb-icon-button{display:flex!important;align-items:center;justify-content:center;width:38px!important;height:38px!important;flex:0 0 38px;font-size:17px!important;line-height:1!important;text-align:center!important;padding:0!important}
.orbiter .orb-status{font-size:11px;color:var(--muted);display:flex;align-items:center;gap:6px}.orbiter .orb-dot{width:5px;height:5px;border-radius:50%;background:#7eb8a4;display:inline-block}.orbiter .orb-dot.idle{background:#9c9d96}.orbiter .orb-tag{font-size:10px;border:1px solid var(--line);padding:2px 6px;border-radius:4px;color:var(--muted)}
.orbiter .orb-tabs{display:flex;gap:6px;margin:18px 0 22px}.orbiter .orb-tabs>*{flex:1;text-align:center!important;font-size:12px!important;padding:7px!important}.orbiter .orb-section{margin:20px 0}.orbiter .orb-section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.orbiter .orb-section-head span{font-size:11px;color:var(--muted)}
.orbiter .orb-row{display:flex;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--line)}.orbiter .orb-condition-icon{width:27px;height:29px;object-fit:contain;opacity:.9;flex:none}.orbiter .orb-fallback{width:27px;text-align:center;color:var(--muted);font-size:22px}.orbiter .orb-details{flex:1;min-width:0}.orbiter .orb-name{font-size:13px;font-weight:600;line-height:1.3;overflow-wrap:anywhere}.orbiter .orb-map{color:var(--muted);font-size:11px;margin-top:3px}.orbiter .orb-time{text-align:right;font-size:11px;white-space:nowrap;font-variant-numeric:tabular-nums}.orbiter .orb-time strong{display:block;font-size:14px;font-weight:550}.orbiter .orb-time small{color:var(--muted);font-size:9px}.orbiter .orb-live .orb-time strong{color:#b4d6c5}.orbiter .orb-star{display:flex!important;align-items:center;justify-content:center;width:28px!important;height:28px!important;flex:0 0 28px;line-height:1!important;border:0!important;background:none!important;padding:3px!important;font-size:15px!important;color:#84928d!important}.orbiter .orb-star.selected{color:var(--accent)!important;background:none!important;border:0!important}
.orbiter .orb-empty{padding:18px 0;color:var(--muted);font-size:12px}.orbiter .orb-message{padding:12px;border:1px solid #e3a07233;border-radius:7px;font-size:12px;color:#d3bda8;margin:16px 0;background:#e3a07208}.orbiter .orb-footer{margin-top:18px}.orbiter .orb-footer>.orb-button+.orb-flex{margin-top:10px}.orbiter .orb-footer .orb-button{width:100%;text-align:center;font-size:12px!important}.orbiter .orb-footnote{font-size:10px;color:var(--muted);margin-top:12px;display:flex;justify-content:space-between;gap:6px}.orbiter .orb-link{color:var(--muted);text-decoration:none}.orbiter .orb-back{margin-bottom:16px!important}.orbiter .orb-subtitle{font-size:12px;color:var(--muted);margin:7px 0 20px!important}
.orbiter .orb-setting{padding:14px 0;border-bottom:1px solid var(--line)}.orbiter .orb-setting .orb-flex>span{font-size:13px;font-weight:550;min-width:0}.orbiter .orb-setting p{font-size:11px;color:var(--muted);margin-top:6px}.orbiter .orb-setting .orb-button{font-size:12px!important}.orbiter .orb-options{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.orbiter .orb-options>*{flex:1 1 85px;white-space:normal!important;overflow-wrap:anywhere;font-size:12px!important}
.orbiter .orb-region-options{display:flex;flex-direction:column;gap:5px;margin-top:10px}.orbiter .orb-region-options .orb-button{display:flex;align-items:center;justify-content:space-between;width:100%;min-height:40px!important;white-space:normal!important;font-size:13px!important}.orbiter .orb-selection-mark{flex:none;color:var(--accent);font-size:14px;line-height:1}
.orbiter .orb-condition-list{margin-top:12px;display:flex;flex-direction:column;gap:7px}.orbiter .orb-condition-choice{border:1px solid var(--line);border-radius:8px;min-width:0;overflow:visible}.orbiter .orb-condition-choice.expanded{border-color:#e3a07244}.orbiter .orb-condition-heading{display:flex;align-items:stretch;gap:0;min-width:0}.orbiter .orb-condition-heading .orb-button{display:flex;align-items:center;gap:10px;border:0!important;background:transparent!important;border-radius:7px!important;padding:10px!important}.orbiter .orb-condition-heading .orb-condition-toggle{flex:1;width:auto;min-width:0!important;white-space:normal!important}.orbiter .orb-condition-heading .orb-condition-toggle.selected{background:#e3a07209!important}.orbiter .orb-condition-choice .orb-condition-icon{width:22px;height:26px;flex:none}.orbiter .orb-condition-copy{display:flex;flex-direction:column;gap:3px;flex:1;min-width:0;text-align:left}.orbiter .orb-choice-name{font-size:13px;font-weight:550;line-height:1.35;overflow-wrap:anywhere}.orbiter .orb-choice-summary{color:var(--muted);font-size:10px;line-height:1.3;overflow-wrap:anywhere}.orbiter .orb-condition-heading .orb-map-expander{flex:0 0 38px;width:38px!important;height:38px!important;align-self:center;justify-content:center;margin-right:6px;border-radius:7px!important;padding:0!important}.orbiter .orb-map-options{display:flex;flex-direction:column;gap:5px;padding:12px;border-top:1px solid var(--line);background:#00000012;border-radius:0 0 8px 8px}.orbiter .orb-map-options h2{font-size:10px;margin-bottom:3px}.orbiter .orb-map-options .orb-button{display:flex;justify-content:space-between;align-items:center;gap:12px;width:100%;min-height:38px!important;text-align:left;white-space:normal!important;font-size:12px!important}.orbiter .orb-map-options .orb-button>span:first-child{min-width:0;overflow-wrap:anywhere}.orbiter .orb-small{font-size:11px;color:var(--muted)}
.orbiter .orb-setup-title{font-size:18px;line-height:1.4;letter-spacing:-.02em;text-transform:none;color:var(--ink);margin-top:28px}.orbiter.orb-setup.orb-wide{max-width:440px}
.orbiter .orb-disclosure-slot{width:38px;height:38px;flex:0 0 38px;display:flex;align-items:center;justify-content:center}.orbiter .orb-chevron{display:block;width:16px;height:16px;flex:none;transform:rotate(0deg);transform-origin:center}.orbiter .orb-chevron.open{transform:rotate(180deg)}.orbiter .orb-disclosure.orb-button{display:flex;align-items:center;justify-content:space-between;gap:0;padding:0!important;white-space:normal!important}.orbiter .orb-disclosure-label{flex:1;min-width:0;text-align:left;padding:9px 11px;overflow-wrap:anywhere}.orbiter .orb-manage{width:100%!important;margin-top:10px;min-height:38px!important}.orbiter .orb-support{border:0!important;background:transparent!important;font-size:11px!important;color:var(--muted)!important;padding:6px!important;white-space:nowrap}.orbiter .orb-notification-details{padding-left:12px;border-left:2px solid #e3a07233;margin:12px 0}.orbiter .orb-notification-details .orb-setting:first-child{padding-top:0}.orbiter .orb-notification-details .orb-setting:last-child{border-bottom:0;padding-bottom:0}
.orbiter.orb-wide{max-width:980px;margin:auto;padding:32px;min-height:100vh}.orbiter.orb-wide .orb-columns{display:grid;grid-template-columns:1fr 1fr;gap:32px}.orbiter.orb-wide .orb-name{font-size:15px}.orbiter.orb-wide .orb-map{font-size:12px}.orbiter .orb-filter-list{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.orbiter .orb-filter-list .orb-button{font-size:11px!important;padding:6px 9px!important}
@media(max-width:650px){.orbiter.orb-wide{padding:20px}.orbiter.orb-wide .orb-columns{display:block}}
`;
